// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purchasing.Infrastructure.Data;

#nullable disable

namespace Purchasing.Infrastructure.Migrations
{
    [DbContext(typeof(PurchasingDbContext))]
    partial class PurchasingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrder", b =>
                {
                    b.Property<string>("POnumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActivationState")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("POnumber");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrderItem", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PurchaseOrderPOnumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("PurchaseOrderPOnumber");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrderItemMapping", b =>
                {
                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerialNumber"));

                    b.Property<string>("PurchaseOrderItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PurchaseOrderPOnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SerialNumber");

                    b.HasIndex("PurchaseOrderItemCode");

                    b.HasIndex("PurchaseOrderPOnumber");

                    b.ToTable("PurchaseOrderItemMapping");
                });

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrderItem", b =>
                {
                    b.HasOne("Purchasing.Domain.Models.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderPOnumber");
                });

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrderItemMapping", b =>
                {
                    b.HasOne("Purchasing.Domain.Models.PurchaseOrderItem", "PurchaseOrderItem")
                        .WithMany("PurchaseOrderItemMappings")
                        .HasForeignKey("PurchaseOrderItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purchasing.Domain.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderItemMappings")
                        .HasForeignKey("PurchaseOrderPOnumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("PurchaseOrderItem");
                });

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PurchaseOrderItemMappings");
                });

            modelBuilder.Entity("Purchasing.Domain.Models.PurchaseOrderItem", b =>
                {
                    b.Navigation("PurchaseOrderItemMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
